name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка зависимостей
      - name: Install dependencies
        run: |
          npm install

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: |
          cat file1.txt file2.txt | grep -q 'Hello world'

      # Шаг 4: Сборка артефактов
      - name: Build artifacts
        run: |
          cat file1.txt file2.txt | gzip > packaged.gz
          
      # Шаг 5: Создание Docker-образа
      - name: Build Docker image
        run: |
          docker build . -t myusername/myapp:${{ github.sha }}

      # Шаг 6: Вход в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 7: Отправка образа в Docker Hub
      - name: Push Docker image
        run: |
          docker push myusername/myapp:${{ github.sha }}
