name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check for 'Hello world in text files
        run: |
          cat file1.txt file2.txt | grep -q 'Hello world'
